### ISSUE TITLE
How to more conveniently use /etc/pmon3/config/app.config.json to manage programs.

### ISSUE THREAD

**Issue by BleethNie** [joe-at-startupmedia/pmon3#30]
I have the following issues. I have a Go web service and three external programs (Redis, Minio, Elasticsearch). I want to use pmon3 to control the start and stop of these four programs. For convenience, I have configured them in the `/etc/pmon3/config/app.config.json` file, and then used `pmon3 init` to start the programs.
- However, I found that the programs did not start. I am not quite clear whether my operation is correct, or how to use logs to query issues during the start-up process.
- Because there is a priority relationship in the start-up of the above programs, pmon3 seems to currently not support the priority feature. Can a "dependency" feature be added (just a personal suggestion for a feature)?
```json
{
    "apps": [
      {
        "file": "/home/golang/app",
        "flags": {
          "name": "mApp",
          "user": "root",
          "log_dir": "/var/log/mApp.log",
          "dependency":["redis","minio","es"]    //other application name
        }
      }
    ]
}
```
- Sometimes I only want to start one of the services above. Is there a command `pmon3 start redis` to only start a single program in `/etc/pmon3/config/app.config.json` (In most scenarios, the programs deployed on the server are actually fixed, using `pmon3 exec` to start a program may be a more cumbersome operation, using `pmon3 start` may be more convenient)?

**Comment by ghost** [comment]
# Issue 1

_However, I found that the programs did not start. I am not quite clear whether my operation is correct, or how to use logs to query issues during the start-up process._

## recent scheme change

Just to make sure, is this something you recently encountered since the 1.14.13 release? If so it's likely due to the fact that the schema changed which resulted in a breaking change. To remedy this, you must delete the sqlite database file before restarting the process.

```bash
systemctl stop pmond
rm -f /etc/pmond/data/data.db
systemctl start pmond
```

## debugging

With regard to logging the process, the easiest way to do this is to start pmond with the following options:
```yaml
log_level: debug
```
OR
```bash
PMON3_DEBUG=true pmond
```

followed by tailing the process logs:
```bash
tail -f /var/log/pmond/*.log
```
AND/OR

```bash
journalctl -u pmond -f
```

# Issue 2
_Because there is a priority relationship in the start-up of the above programs, pmon3 seems to currently not support the priority feature. Can a "dependency" feature be added (just a personal suggestion for a feature)?_

I think this would be a useful feature, I've ran into scenario where I need it for myself. In addition to `dependencies` it would probably also be helpful to also use a `priority` property. I will create a separate issue to work on that

# Issue 3

_Sometimes I only want to start one of the services above. Is there a command pmon3 start redis to only start a single program in /etc/pmon3/config/app.config.json (In most scenarios, the programs deployed on the server are actually fixed, using pmon3 exec to start a program may be a more cumbersome operation, using pmon3 start may be more convenient)?_


https://github.com/joe-at-startupmedia/pmon3?tab=readme-ov-file#applications-config

PMON3 currently prefers the SQLite database over the Apps config and only refers to the Apps config when the database doesn't exist or is empty. This is explained in further detail in the link above. Personally, I think this logic could use some improvement or at least the offering of a configuration parameter to always prefer the Apps Config over the database file. 

To answer your question, `start` operates on processes saved in the database, not the Apps Config file (although the process in the database are a result of the Apps Config spec). As such yes, you can use `start` to start a single program but you would have to first `kill` all of the existing process. The database saves the state of the process which is persisted across run sessions.

The difference between `start` and `exec` is that `exec` inserts a new process into the database. If you're using the Apps Config feature, you'd want to instead place the process spec in Apps Config instead of using the `exec` command, this way the Apps Config serves as a single source of truth.

--- 

Keep in mind, with more configuration comes more complexity and more complexity = less usability for general users.

**Comment by BleethNie** [comment]
Thank you very much for your patient answers to my questions, which have been very helpful to me. For question 3, I would like to add some new ideas to see if it can change some of your thoughts:

- For using the apps config file and executing the start command, the flowchart is as follows:

![image](https://github.com/user-attachments/assets/3b8be5d0-e019-4cf0-9dc0-3ee8f641dae2)

Here, the apps config is just an entry point for quick startup, and the state saving is still in the database.


- For using the apps config file and executing the init command, the flowchart is as follows:

![image](https://github.com/user-attachments/assets/a7050b7e-bc22-428b-8b05-5ef997ead365)

Here, the init command and the start command have the same functionality, but the init is a cyclic operation, so the start command will not increase complexity.

**Comment by ghost** [comment]
`start` is currently simply an alias of `restart`. So treating it different from `restart` would entail breaking it into a separate cli command. This however would be unnecessary because they basically do the same thing which justifies them being an alias of eachother. Adding the ability to refer to an apps-config entry  is still possible without separating the two.

The only scenario I foresee the applicability of referencing an apps-config entry would be when a config entry is added while the pmond is running without restart the process.

- [x] don't increment the restart counter when the `start` alias is used
- [x] provide an `--apps-config` flag to the `init` command to only load from the apps-config
- [x] by default start apps from the apps-config in addition to stopped processes in the database

**Comment by ghost** [comment]
@BleethNie I'll be testing this release candidate out over the next week before merging into master. It should meet most of the requirements discussed above:
https://github.com/joe-at-startupmedia/pmon3/releases/tag/v1.15.0-alpha.1

**Comment by BleethNie** [comment]
It's very wonderful，I will also test whether the relevant functions are normal on my server

**Comment by BleethNie** [comment]
In my development environment, the program executes correctly using the apps config
